/**
 * Cloudflare Worker entry point.
 * Wraps the OpenNext handler and adds the scheduled (cron) handler.
 */

import { handleScheduledEvent } from "./src/worker-scheduled";

// Import the OpenNext worker's fetch handler
// @ts-ignore — generated by opennextjs-cloudflare build
import nextWorker from "./.open-next/worker.js";

export default {
  // Pass through all fetch requests to the OpenNext handler
  fetch: nextWorker.fetch,

  // Handle cron triggers for the auto-dialer
  async scheduled(
    controller: ScheduledController,
    env: Record<string, unknown>,
    ctx: ExecutionContext
  ): Promise<void> {
    await handleScheduledEvent(env, ctx);
  },
};
